In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(r'Student_sheet_Output - Sheet1.csv')
df

,NAME,Question1,Question2,Question3,Question4,Question5,Question7,Question8,Question9,Question10,...,Question18,Question19,Question20,Question21,Question22,Question23,Question24,Question25,Question26,Question27
0,anj,0,1,0,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0.0,0,0
1,bus,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0,1
2,sk,1,1,1,1,1,1,1,1,1,...,1,0,0,0,0,0,0,0.0,0,1
3,nir,1,1,1,1,1,1,1,1,1,...,1,0,0,0,0,0,0,0.0,0,1
4,dra,1,1,1,1,1,1,1,1,1,...,1,0,0,0,0,0,0,0.0,0,1
5,ngh,1,1,1,1,1,1,1,1,1,...,1,0,0,0,0,0,0,0.0,0,1
6,nav,1,1,1,1,1,1,0,0,0,...,1,0,0,0,0,0,0,0.0,0,0
7,kar,0,1,0,1,0,1,1,1,0,...,1,0,0,0,0,0,0,0.0,0,1
8,aar,0,1,0,1,0,1,1,1,0,...,1,1,1,1,0,0,0,1.0,0,1
9,gir,0,1,0,1,1,1,1,0,1,...,1,0,0,0,0,0,0,0.0,0,1
10,ari,0,1,1,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0.0,0,1
11,kal,1,1,1,1,1,1,1,1,1,...,1,0,0,1,1,1,0,0.0,0,1
12,thi,1,1,0,1,1,1,0,1,1,...,1,0,0,0,0,0,0,0.0,0,1
13,iah,0,1,0,1,1,1,1,1,0,...,1,0,0,0,0,0,0,0.0,0,1
14,abm,0,1,0,1,0,1,1,1,0,...,1,1,1,0,0,1,0,0.0,0,1
15,sha,0,1,0,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0.0,0,0
16,lms,0,1,0,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0.0,0,0
17,swa,0,1,0,1,1,1,1,0,0,...,1,0,0,0,0,0,0,0.0,0,1
18,rma,1,1,1,1,1,1,1,1,1,...,1,0,0,0,0,0,0,0.0,1,1
19,ain,0,1,0,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0.0,0,0
20,ama,1,1,0,1,1,1,0,1,1,...,1,0,0,0,0,0,0,0.0,0,0
21,van,1,1,1,1,1,1,1,1,1,...,1,0,0,0,0,1,0,0.0,0,1
22,ss,0,1,1,1,1,1,1,1,1,...,1,0,0,0,0,0,0,NaN,0,1
23,yay,1,1,0,1,1,1,0,1,1,...,1,0,0,0,0,0,0,0.0,0,1
24,nda,1,1,0,1,0,1,1,1,1,...,0,1,0,1,0,1,0,0.0,1,1
25,thi,1,1,1,1,1,1,1,1,1,...,1,0,0,1,0,1,0,0.0,0,0
26,vam,0,1,1,1,1,1,0,1,1,...,1,0,0,0,0,0,0,0.0,0,1
27,nti,1,1,0,1,1,1,1,1,1,...,1,0,0,0,0,0,0,0.0,0,1
28,thy,0,1,0,1,0,1,0,1,0,...,1,0,0,0,0,0,0,0.0,0,1
29,ndr,0,1,0,1,1,1,0,1,0,...,1,0,0,0,0,0,0,0.0,0,1
30,ath,1,1,0,1,1,1,1,1,1,...,1,0,0,0,0,0,0,0.0,0,1
31,ach,0,1,1,1,0,1,0,0,1,...,1,0,0,0,0,1,0,0.0,1,1
32,heg,0,1,1,1,1,1,1,1,1,...,1,0,1,0,1,0,0,0.0,0,1
33,yil,0,1,0,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0.0,0,1
34,ala,1,1,0,1,1,1,1,1,0,...,1,0,0,0,0,0,0,0.0,0,1
35,han,1,1,1,1,1,1,0,1,1,...,1,0,0,0,0,1,0,0.0,0,1
36,bu2,0,1,1,1,1,1,1,1,1,...,1,0,1,0,1,1,0,0.0,1,1
37,uda,1,1,1,1,1,1,1,1,1,...,1,0,0,0,0,0,0,0.0,0,1
38,udk,0,1,0,1,1,1,1,1,1,...,1,0,1,0,0,1,0,0.0,1,1
39,und,1,1,1,1,1,1,1,1,0,...,1,0,0,0,0,1,0,0.0,0,1
40,hya,0,1,1,1,1,0,1,1,1,...,1,0,0,0,0,0,0,0.0,0,1
41,han,1,1,0,1,1,1,1,1,1,...,1,0,1,0,1,0,0,0.0,0,1
42,phr,0,1,0,1,0,1,1,1,1,...,1,0,0,0,1,1,0,0.0,1,1
43,ant,0,1,1,1,0,1,1,1,1,...,1,0,0,0,1,1,0,0.0,0,1

In [2]:
df.describe()

,Question1,Question2,Question3,Question4,Question5,Question7,Question8,Question9,Question10,Question11,...,Question18,Question19,Question20,Question21,Question22,Question23,Question24,Question25,Question26,Question27
count,44.000000,44.0,44.000000,44.0,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,...,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.0,43.000000,44.000000,44.000000
mean,0.477273,1.0,0.454545,1.0,0.750000,0.954545,0.659091,0.840909,0.659091,0.886364,...,0.818182,0.068182,0.136364,0.090909,0.136364,0.272727,0.0,0.023256,0.136364,0.840909
std,0.505258,0.0,0.503686,0.0,0.438019,0.210707,0.479495,0.369989,0.479495,0.321038,...,0.390154,0.254972,0.347142,0.290803,0.347142,0.450511,0.0,0.152499,0.347142,0.369989
min,0.000000,1.0,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
25%,0.000000,1.0,0.000000,1.0,0.750000,1.000000,0.000000,1.000000,0.000000,1.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.000000
50%,0.000000,1.0,0.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.000000
75%,1.000000,1.0,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.0,0.000000,0.000000,1.000000
max,1.000000,1.0,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000

In [8]:


# Calculate total score per person
df["total_score"] = df.loc[:, "Question1":"Question27"].sum(axis=1)

# Calculate percentage score
df["percentage"] = df["total_score"] / 28 * 100

# Item analysis: how many people got each question correct
item_analysis = df.loc[:, "Question1":"Question27"].sum(axis=0)

print(item_analysis)

Question1     21.0
Question2     44.0
Question3     20.0
Question4     44.0
Question5     33.0
Question7     42.0
Question8     29.0
Question9     37.0
Question10    29.0
Question11    39.0
Question12    32.0
Question13    37.0
Question14    34.0
Question15    34.0
Question16    29.0
Question17    42.0
Question18    36.0
Question19     3.0
Question20     6.0
Question21     4.0
Question22     6.0
Question23    12.0
Question24     0.0
Question25     1.0
Question26     6.0
Question27    37.0
dtype: float64

In [13]:


# Calculate total score for each student
df["total_score"] = df.loc[:, "Question1":"Question27"].sum(axis=1)

# Preview results
print(df[["NAME", "total_score"]])

   NAME  total_score
0   anj          8.0
1   bus          4.0
2    sk         18.0
3   nir         18.0
4   dra         18.0
5   ngh         18.0
6   nav         10.0
7   kar         11.0
8   aar         16.0
9   gir         13.0
10  ari         14.0
11  kal         20.0
12  thi         15.0
13  iah         13.0
14  abm         17.0
15  sha         11.0
16  lms         12.0
17  swa         14.0
18  rma         18.0
19  ain         10.0
20  ama         14.0
21  van         17.0
22   ss         15.0
23  yay         13.0
24  nda         18.0
25  thi         18.0
26  vam         15.0
27  nti         17.0
28  thy         10.0
29  ndr         13.0
30  ath         16.0
31  ach         13.0
32  heg         18.0
33  yil         12.0
34  ala         13.0
35  han         18.0
36  bu2         20.0
37  uda         16.0
38  udk         18.0
39  und         17.0
40  hya         14.0
41  han         19.0
42  phr         17.0
43  ant         18.0

In [15]:
df["percentage"] = (df["total_score"] / 28) * 100

print(df[["NAME", "total_score", "percentage"]])

   NAME  total_score  percentage
0   anj          8.0   28.571429
1   bus          4.0   14.285714
2    sk         18.0   64.285714
3   nir         18.0   64.285714
4   dra         18.0   64.285714
5   ngh         18.0   64.285714
6   nav         10.0   35.714286
7   kar         11.0   39.285714
8   aar         16.0   57.142857
9   gir         13.0   46.428571
10  ari         14.0   50.000000
11  kal         20.0   71.428571
12  thi         15.0   53.571429
13  iah         13.0   46.428571
14  abm         17.0   60.714286
15  sha         11.0   39.285714
16  lms         12.0   42.857143
17  swa         14.0   50.000000
18  rma         18.0   64.285714
19  ain         10.0   35.714286
20  ama         14.0   50.000000
21  van         17.0   60.714286
22   ss         15.0   53.571429
23  yay         13.0   46.428571
24  nda         18.0   64.285714
25  thi         18.0   64.285714
26  vam         15.0   53.571429
27  nti         17.0   60.714286
28  thy         10.0   35.714286
29  ndr         13.0   46.428571
30  ath         16.0   57.142857
31  ach         13.0   46.428571
32  heg         18.0   64.285714
33  yil         12.0   42.857143
34  ala         13.0   46.428571
35  han         18.0   64.285714
36  bu2         20.0   71.428571
37  uda         16.0   57.142857
38  udk         18.0   64.285714
39  und         17.0   60.714286
40  hya         14.0   50.000000
41  han         19.0   67.857143
42  phr         17.0   60.714286
43  ant         18.0   64.285714

In [26]:
# Classify students based on percentage 
def classify(pct):
    if pct >= 60: 
        return "Advanced"
    elif pct >= 50: 
        return "Upper Intermediate"
    elif pct >= 40: 
        return "Intermediate"
    else: 
        return "Beginner" 
df["level"] = df["percentage"].apply(classify) 
# Preview results
print(df[["NAME", "total_score", "percentage", "level"]])

   NAME  total_score  percentage               level
0   anj          8.0   28.571429            Beginner
1   bus          4.0   14.285714            Beginner
2    sk         18.0   64.285714            Advanced
3   nir         18.0   64.285714            Advanced
4   dra         18.0   64.285714            Advanced
5   ngh         18.0   64.285714            Advanced
6   nav         10.0   35.714286            Beginner
7   kar         11.0   39.285714            Beginner
8   aar         16.0   57.142857  Upper Intermediate
9   gir         13.0   46.428571        Intermediate
10  ari         14.0   50.000000  Upper Intermediate
11  kal         20.0   71.428571            Advanced
12  thi         15.0   53.571429  Upper Intermediate
13  iah         13.0   46.428571        Intermediate
14  abm         17.0   60.714286            Advanced
15  sha         11.0   39.285714            Beginner
16  lms         12.0   42.857143        Intermediate
17  swa         14.0   50.000000  Upper Intermediate
18  rma         18.0   64.285714            Advanced
19  ain         10.0   35.714286            Beginner
20  ama         14.0   50.000000  Upper Intermediate
21  van         17.0   60.714286            Advanced
22   ss         15.0   53.571429  Upper Intermediate
23  yay         13.0   46.428571        Intermediate
24  nda         18.0   64.285714            Advanced
25  thi         18.0   64.285714            Advanced
26  vam         15.0   53.571429  Upper Intermediate
27  nti         17.0   60.714286            Advanced
28  thy         10.0   35.714286            Beginner
29  ndr         13.0   46.428571        Intermediate
30  ath         16.0   57.142857  Upper Intermediate
31  ach         13.0   46.428571        Intermediate
32  heg         18.0   64.285714            Advanced
33  yil         12.0   42.857143        Intermediate
34  ala         13.0   46.428571        Intermediate
35  han         18.0   64.285714            Advanced
36  bu2         20.0   71.428571            Advanced
37  uda         16.0   57.142857  Upper Intermediate
38  udk         18.0   64.285714            Advanced
39  und         17.0   60.714286            Advanced
40  hya         14.0   50.000000  Upper Intermediate
41  han         19.0   67.857143            Advanced
42  phr         17.0   60.714286            Advanced
43  ant         18.0   64.285714            Advanced

In [27]:
df.to_csv("student_scores.csv", index=False)

print("Excel file 'student_scores.xlsx' has been created successfully!")

Excel file 'student_scores.xlsx' has been created successfully!

In [28]:
!pip install openpyxl
df.to_excel("student_scores.xlsx", index=False)

Requirement already satisfied: openpyxl in c:\program files\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\program files\python312\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
level_counts = df["level"].value_counts() 
print(level_counts)

level
Advanced              19
Upper Intermediate    10
Intermediate           8
Beginner               7
Name: count, dtype: int64